int inicializar(Fantasma array[], int size);
int publicidad_Inicializar(Publicidad array[], int size);
int fantasma_buscarEmpty(Fantasma array[], int size, int* posicion);
int publicidad_buscarEmpty(Publicidad array[], int size, int* posicion);
int fantasma_buscarID(Fantasma array[], int size, int valorBuscado, int* posicion);
int publicidad_buscarID(Publicidad array[], int size, int valorBuscado, int* posicion);
int fantasma_buscarInt(Fantasma array[], int size, int valorBuscado, int* posicion);
int fantasma_buscarString(Fantasma array[], int size, char* valorBuscado, int* indice);
int publicidad_buscarCUIT(Publicidad array[], int size,char* valorBuscado, int* posicion);
int fantasma_alta(Fantasma array[], int size, int* contadorID);
int pantalla_contratar(Publicidad array[], int size);
int fantasma_baja(Fantasma array[], int sizeArray);
int fantasma_bajaValorRepetidoInt(Fantasma array[], int sizeArray, int valorBuscado);
int fantasma_modificar(Fantasma array[], int sizeArray);
int sort(Fantasma* list, int len);
int publicidad_ordenarPorCuit(Publicidad array[],int size);
int fantasma_listar(Fantasma array[], int size);
int publicidad_listarPorCuit(Publicidad array[],int size,char* aCuit);
void setPantalla(Pantalla arrayPantalla[], int buscarEmpty, int idPantallAux, char tipoAux[], char nombreAux[], float precioPorDiaAux, char direccionAux[]);
void setPublicidad(Publicidad arrayPublicidad[], int buscarEmpty,char cuitAux[],int idPantallaAux, int cantDiasAux, char archivoAux[]);
int publicidad_consultaFacturacion(Pantalla arrayPantalla[],int sizePantalla,Publicidad arrayPublicidad[],int sizePublicidad);
int publicidad_calcularFacturacion(Pantalla arrayPantalla[],int sizePantalla,Publicidad arrayPublicidad[],int sizePublicidad,char* aCuit, int *cantidadContrataciones);
int validateData(Employee* list, int len);
