int controller_loadFromText(char* path , LinkedList* pListaEmpleados);
int controller_loadFromBinary(char* path , LinkedList* pListaEmpleados);
int controller_lastIdEmployee(LinkedList* pListaEmpleados);
int controller_searchEmployeeById(LinkedList* pListaEmpleados, int id, int* index);
int controller_addEmployee(LinkedList* pListaEmpleados);
int controller_editEmployee(LinkedList* pListaEmpleados);
int controller_removeEmployee(LinkedList* pListaEmpleados);
int controller_ListEmployee(LinkedList* pListaEmpleados);
int controller_PrintEmployee(LinkedList* pListaEmpleados, int index);
int controller_sortEmployee(LinkedList* pListaEmpleados);
int controller_saveAsText(char* path , LinkedList* pListaEmpleados);
int controller_saveAsBinary(char* path , LinkedList* pListaEmpleados);
